version: "3.9"
services:
  laravel:
    build:
      context: "./php8.1"
    container_name: "laravel"
    volumes:
      - "${LARAVEL_APP_PATH}:/var/www/html"
      - "./php8.1/config/php.ini:/usr/local/etc/php/php.ini"
      - "./php8.1/apache/config/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    restart: always
    extra_hosts:
      - "laravel.test:127.0.0.1"
    hostname: laravel.test
    domainname: test
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql/
    ports:
      - "3306:3306"
    env_file:
      - .env
  jenkins:
    build:
      context: ./jenkins
    restart: always
    container_name: jenkins
    volumes:
      - ./jenkins/jenkins-home:/var/jenkins_home/
    ports:
      - "8080:8080"
      - "5000:5000"
    user: root